name: Greenie

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  
concurrency:
  group: auto-commit
  cancel-in-progress: true
  
jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate real work
        run: |
          FILES=("learning.md" "notes.md" "ideas.md")
          MESSAGES=("learned something new" "worked on project" "improved code" "fixed bug" "daily progress" "learning" "learning cloud" "working" "learning guitar" "did some more" "practice today" "helloworld" "hello world" "faded" "you" "were" "the shadow" "to my light" "did you feel us"  "another star" "you fade away" "where are you now" "another dream" "the monster running wild insde of me" "im faded" "oh where oh where my baby be" "the world needs him when there aint enough" "but look where do we got" "i tried so hard and got so far" "end the end it doesn't even matter" "i ve putu my trust in you pusehd as far as i cann go" "for all this theres only one thing you should know" "i tried so hard and got" "so faaaarrrrrrr")

          FILE=${FILES[$RANDOM % ${#FILES[@]}]}
          MSG=${MESSAGES[$RANDOM % ${#MESSAGES[@]}]}

          echo "- $(date): practiced DevOps and CI/CD" >> $FILE

      - name: Commit
        run: |
          git config --global user.name "acerijan"
          git config --global user.email "rijandai147@gmail.com"
          git add .
          git commit -m "$MSG $(date)" || echo "no changes"

      - name: Push
        run: |
          git pull --rebase origin main
          git push
